apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-repeater-db
  namespace: skill-repeater
  labels:
    app: skill-repeater-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-repeater-db
  template:
    metadata:
      labels:
        app: skill-repeater-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: skill-repeater-config
              key: SKILL_REPEATER_DATABASE_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: skill-repeater-config
              key: SKILL_REPEATER_DATABASE_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skill-repeater-secrets
              key: DATASOURCE_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data/pgdata
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - "${SKILL_REPEATER_DATABASE_USER}"
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: skill-repeater-db
  namespace: skill-repeater
  labels:
    app: skill-repeater-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: skill-repeater-db 